// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Provides personalized career recommendations and skill assessments based on user's recorded career aspirations and concerns.
 *
 * - voiceCareerConsultation - A function that handles the voice-based career consultation process.
 * - VoiceCareerConsultationInput - The input type for the voiceCareerConsultation function.
 * - VoiceCareerConsultationOutput - The return type for the voiceCareerConsultation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const VoiceCareerConsultationInputSchema = z.object({
  audioDataUri: z
    .string()
    .describe(
      "A recording of the user's career aspirations and concerns, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type VoiceCareerConsultationInput = z.infer<typeof VoiceCareerConsultationInputSchema>;

const VoiceCareerConsultationOutputSchema = z.object({
  analysis: z.string().describe('The AI analysis of the user audio recording.'),
  recommendations: z.string().describe('Personalized career recommendations.'),
  skillAssessments: z.string().describe('Skill assessments based on the user input.'),
  podcastRecommendations: z.string().describe('Podcast recommendations for the user.'),
});
export type VoiceCareerConsultationOutput = z.infer<typeof VoiceCareerConsultationOutputSchema>;

export async function voiceCareerConsultation(
  input: VoiceCareerConsultationInput
): Promise<VoiceCareerConsultationOutput> {
  return voiceCareerConsultationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'voiceCareerConsultationPrompt',
  input: {schema: VoiceCareerConsultationInputSchema},
  output: {schema: VoiceCareerConsultationOutputSchema},
  prompt: `You are an AI career advisor specializing in providing personalized recommendations and skill assessments based on user's recorded career aspirations and concerns.

Analyze the user's recording and provide personalized recommendations and skill assessments.
Also provide podcast recommendations.

User Recording: {{media url=audioDataUri}}

Output in the following format:
Analysis: [AI analysis of the user audio recording]
Recommendations: [Personalized career recommendations]
Skill Assessments: [Skill assessments based on the user input]
Podcast Recommendations: [Podcast recommendations for the user]`,
});

const voiceCareerConsultationFlow = ai.defineFlow(
  {
    name: 'voiceCareerConsultationFlow',
    inputSchema: VoiceCareerConsultationInputSchema,
    outputSchema: VoiceCareerConsultationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
